/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frame;

/**
 *
 * @author This PC
 */
public class pn_dataprestasi extends javax.swing.JPanel {

    /**
     * Creates new form pn_dataprestasi
     */
    public pn_dataprestasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t_idanggota = new javax.swing.JTextField();
        t_anggota = new javax.swing.JTextField();
        c_tingkatan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_catatan = new javax.swing.JTextArea();
        b_simpan = new javax.swing.JButton();
        b_kembali = new javax.swing.JButton();
        b_ubah = new javax.swing.JButton();
        b_hapus = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("EDIT DATA PRESTASI ");

        t_idanggota.setBorder(javax.swing.BorderFactory.createTitledBorder("ID Anggota"));

        t_anggota.setBorder(javax.swing.BorderFactory.createTitledBorder("Nama Anggota"));

        c_tingkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kecamatan", "Kabupaten", "Provinsi" }));
        c_tingkatan.setBorder(javax.swing.BorderFactory.createTitledBorder("Tingkat"));

        t_catatan.setColumns(20);
        t_catatan.setRows(5);
        t_catatan.setBorder(javax.swing.BorderFactory.createTitledBorder("Catatan"));
        jScrollPane1.setViewportView(t_catatan);

        b_simpan.setBackground(new java.awt.Color(0, 0, 255));
        b_simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_simpan.setForeground(new java.awt.Color(255, 255, 255));
        b_simpan.setText("Simpan");

        b_kembali.setBackground(new java.awt.Color(0, 255, 102));
        b_kembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_kembali.setForeground(new java.awt.Color(255, 255, 255));
        b_kembali.setText("Kembali");

        b_ubah.setBackground(new java.awt.Color(255, 204, 0));
        b_ubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_ubah.setForeground(new java.awt.Color(255, 255, 255));
        b_ubah.setText("Ubah");

        b_hapus.setBackground(new java.awt.Color(255, 51, 0));
        b_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_hapus.setForeground(new java.awt.Color(255, 255, 255));
        b_hapus.setText("Hapus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_idanggota)
                            .addComponent(t_anggota)
                            .addComponent(c_tingkatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_ubah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_kembali))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(t_idanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(c_tingkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_simpan)
                    .addComponent(b_kembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_ubah)
                    .addComponent(b_hapus))
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_hapus;
    private javax.swing.JButton b_kembali;
    private javax.swing.JButton b_simpan;
    private javax.swing.JButton b_ubah;
    private javax.swing.JComboBox<String> c_tingkatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_anggota;
    private javax.swing.JTextArea t_catatan;
    private javax.swing.JTextField t_idanggota;
    // End of variables declaration//GEN-END:variables
}
